export type ConfigScope = 'global' | 'supplier' | 'category' | 'product' | 'run';
export type SettingType = 'boolean' | 'number' | 'string' | 'enum' | 'string-list';

export interface SettingDefinition<T = unknown> {
  key: string; category: string; type: SettingType; defaultValue: T; allowedValues?: readonly string[]; min?: number; max?: number; unit?: string; scopes: readonly ConfigScope[]; confirmationRequired: boolean; impactPreviewRequired: boolean; helpText: string; audit: 'none' | 'change' | 'security'; schemaVersion: number; migration: 'preserve' | 'reset' | 'locked'; locked: boolean;
}

const scopeAll = ['global', 'supplier', 'category', 'product', 'run'] as const;
const globalRun = ['global', 'run'] as const;
export const CONFIG_SCHEMA_VERSION = 1;

export const SETTING_REGISTRY = [
  { key: 'pricing.markupPercent', category: 'Pricing and tax', type: 'number', defaultValue: 30, min: 0, max: 300, unit: '%', scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.markupPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.costFloorPercent', category: 'Pricing and tax', type: 'number', defaultValue: 30, min: 0, max: 300, unit: '%', scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.costFloorPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.fixedAddAmount', category: 'Pricing and tax', type: 'number', defaultValue: 0, min: 0, max: 10000, unit: 'AUD', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.fixedAddAmount control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.targetMarginPercent', category: 'Pricing and tax', type: 'number', defaultValue: 23.08, min: 0, max: 95, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.targetMarginPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.competitorUndercutAmount', category: 'Pricing and tax', type: 'number', defaultValue: 1, min: 0, max: 500, unit: 'AUD', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.competitorUndercutAmount control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.competitorUndercutPercent', category: 'Pricing and tax', type: 'number', defaultValue: 5, min: 0, max: 50, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.competitorUndercutPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.minimumDollarMargin', category: 'Pricing and tax', type: 'number', defaultValue: 0, min: 0, max: 10000, unit: 'AUD', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.minimumDollarMargin control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.gstRate', category: 'Pricing and tax', type: 'number', defaultValue: 10, min: 0, max: 25, unit: '%', scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.gstRate control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.decimalPlaces', category: 'Pricing and tax', type: 'number', defaultValue: 2, min: 0, max: 4, unit: 'places', scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.decimalPlaces control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.roundingIncrement', category: 'Pricing and tax', type: 'number', defaultValue: 0.01, min: 0.01, max: 1, unit: 'AUD', scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.roundingIncrement control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.minimumSellPrice', category: 'Pricing and tax', type: 'number', defaultValue: 0, min: 0, max: 10000, unit: 'AUD', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.minimumSellPrice control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.maxAutoIncreasePercent', category: 'Pricing and tax', type: 'number', defaultValue: 15, min: 0, max: 200, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.maxAutoIncreasePercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.maxAutoDecreasePercent', category: 'Pricing and tax', type: 'number', defaultValue: 10, min: 0, max: 100, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.maxAutoDecreasePercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.materialChangeTolerance', category: 'Pricing and tax', type: 'number', defaultValue: 0.01, min: 0, max: 100, unit: 'AUD', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.materialChangeTolerance control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.approvalThresholdPercent', category: 'Pricing and tax', type: 'number', defaultValue: 10, min: 0, max: 100, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'pricing.approvalThresholdPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.strategy', category: 'Pricing and tax', type: 'enum', defaultValue: 'MARKUP_ON_COST', allowedValues: ['MARKUP_ON_COST', 'FIXED_ADD', 'TARGET_MARGIN', 'COMPETITOR_MATCH', 'UNDERCUT_AMOUNT', 'UNDERCUT_PERCENT', 'MAINTAIN_FLOOR'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.strategy control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.inputGstBasis', category: 'Pricing and tax', type: 'enum', defaultValue: 'ex-gst', allowedValues: ['ex-gst', 'inc-gst', 'unknown'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.inputGstBasis control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.outputGstBasis', category: 'Pricing and tax', type: 'enum', defaultValue: 'ex-gst', allowedValues: ['ex-gst', 'inc-gst'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.outputGstBasis control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.roundingMethod', category: 'Pricing and tax', type: 'enum', defaultValue: 'HALF_UP', allowedValues: ['HALF_UP', 'UP', 'DOWN'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.roundingMethod control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.currency', category: 'Pricing and tax', type: 'enum', defaultValue: 'AUD', allowedValues: ['AUD'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.currency control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'pricing.priceFreezeState', category: 'Pricing and tax', type: 'enum', defaultValue: 'off', allowedValues: ['off', 'manual-review', 'freeze'], scopes: scopeAll, confirmationRequired: true, impactPreviewRequired: true, helpText: 'pricing.priceFreezeState control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.maxFileMb', category: 'File parsing', type: 'number', defaultValue: 25, min: 1, max: 50, unit: 'MB', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.maxFileMb control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.maxRows', category: 'File parsing', type: 'number', defaultValue: 50000, min: 1, max: 50000, unit: 'rows', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.maxRows control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.maxSheets', category: 'File parsing', type: 'number', defaultValue: 20, min: 1, max: 50, unit: 'sheets', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.maxSheets control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.maxColumns', category: 'File parsing', type: 'number', defaultValue: 100, min: 1, max: 200, unit: 'columns', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.maxColumns control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.maxCells', category: 'File parsing', type: 'number', defaultValue: 1000000, min: 1, max: 2000000, unit: 'cells', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.maxCells control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.previewRows', category: 'File parsing', type: 'number', defaultValue: 25, min: 5, max: 200, unit: 'rows', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.previewRows control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.headerRow', category: 'File parsing', type: 'number', defaultValue: 1, min: 1, max: 100, unit: 'row', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.headerRow control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.rowsToSkip', category: 'File parsing', type: 'number', defaultValue: 0, min: 0, max: 100, unit: 'rows', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.rowsToSkip control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.acceptedTypes', category: 'File parsing', type: 'enum', defaultValue: 'csv,xlsx', allowedValues: ['csv', 'xlsx', 'csv,xlsx'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.acceptedTypes control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.csvDelimiter', category: 'File parsing', type: 'enum', defaultValue: 'auto', allowedValues: [',', ';', 'tab', 'auto'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.csvDelimiter control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.encoding', category: 'File parsing', type: 'enum', defaultValue: 'utf-8', allowedValues: ['utf-8', 'utf-8-sig', 'windows-1252'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.encoding control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.quoteCharacter', category: 'File parsing', type: 'enum', defaultValue: 'double-quote', allowedValues: ['double-quote', 'single-quote'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.quoteCharacter control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.decimalSeparator', category: 'File parsing', type: 'enum', defaultValue: '.', allowedValues: ['.', ','], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.decimalSeparator control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.thousandsSeparator', category: 'File parsing', type: 'enum', defaultValue: ',', allowedValues: [',', '.', 'space', 'none'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.thousandsSeparator control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.blankRowBehaviour', category: 'File parsing', type: 'enum', defaultValue: 'skip', allowedValues: ['skip', 'keep', 'stop'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.blankRowBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.dateFormat', category: 'File parsing', type: 'enum', defaultValue: 'auto', allowedValues: ['auto', 'yyyy-mm-dd', 'dd/mm/yyyy'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.dateFormat control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'files.duplicateRowBehaviour', category: 'File parsing', type: 'enum', defaultValue: 'block', allowedValues: ['block', 'warn', 'keep-first'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'files.duplicateRowBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'automation.profileMatchThreshold', category: 'File-role and mapping automation', type: 'number', defaultValue: 0.95, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'automation.profileMatchThreshold control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'automation.sheetSelectionThreshold', category: 'File-role and mapping automation', type: 'number', defaultValue: 0.9, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'automation.sheetSelectionThreshold control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'automation.mappingThreshold', category: 'File-role and mapping automation', type: 'number', defaultValue: 0.95, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'automation.mappingThreshold control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.descriptionSuggestionThreshold', category: 'Matching', type: 'number', defaultValue: 0.82, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.descriptionSuggestionThreshold control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.ambiguityDelta', category: 'Matching', type: 'number', defaultValue: 0.05, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.ambiguityDelta control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.maxSuggestedCandidates', category: 'Matching', type: 'number', defaultValue: 5, min: 1, max: 20, unit: 'candidates', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.maxSuggestedCandidates control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.priceIncreaseWarnPercent', category: 'Validation', type: 'number', defaultValue: 20, min: 0, max: 300, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.priceIncreaseWarnPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.priceDecreaseWarnPercent', category: 'Validation', type: 'number', defaultValue: 15, min: 0, max: 100, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.priceDecreaseWarnPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.outlierThresholdPercent', category: 'Validation', type: 'number', defaultValue: 50, min: 0, max: 500, unit: '%', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.outlierThresholdPercent control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.stalenessDays', category: 'Validation', type: 'number', defaultValue: 30, min: 1, max: 365, unit: 'days', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.stalenessDays control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.bulkActionMaximum', category: 'Workflow', type: 'number', defaultValue: 100, min: 1, max: 500, unit: 'records', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.bulkActionMaximum control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.paginationSize', category: 'Workflow', type: 'number', defaultValue: 50, min: 10, max: 500, unit: 'rows', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.paginationSize control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.undoHistoryDepth', category: 'Workflow', type: 'number', defaultValue: 50, min: 1, max: 200, unit: 'actions', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.undoHistoryDepth control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.snapshotRetentionDays', category: 'Privacy', type: 'number', defaultValue: 30, min: 1, max: 365, unit: 'days', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.snapshotRetentionDays control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.auditRetentionDays', category: 'Privacy', type: 'number', defaultValue: 365, min: 1, max: 3650, unit: 'days', scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.auditRetentionDays control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.validityDays', category: 'Competitor', type: 'number', defaultValue: 30, min: 1, max: 365, unit: 'days', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.validityDays control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.matchConfidenceThreshold', category: 'Competitor', type: 'number', defaultValue: 0.8, min: 0, max: 1, unit: 'score', scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.matchConfidenceThreshold control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'automation.autoApplyConfirmedMappings', category: 'File-role and mapping automation', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'automation.autoApplyConfirmedMappings control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'automation.newSuggestionsRequireConfirmation', category: 'File-role and mapping automation', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'automation.newSuggestionsRequireConfirmation control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.aliasUse', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.aliasUse control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.caseNormalisation', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.caseNormalisation control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.whitespaceNormalisation', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.whitespaceNormalisation control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.brandMatching', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.brandMatching control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.gtinMatching', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.gtinMatching control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.packSizeMatching', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.packSizeMatching control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.fuzzySuggestions', category: 'Matching', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.fuzzySuggestions control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.autoCompareAfterMapping', category: 'Workflow', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.autoCompareAfterMapping control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.restoreLastSupplierProfile', category: 'Workflow', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.restoreLastSupplierProfile control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.oneClickRepeatRun', category: 'Workflow', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.oneClickRepeatRun control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.autoSelectEligibleExactMatches', category: 'Workflow', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.autoSelectEligibleExactMatches control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'workflow.automaticApproval', category: 'Workflow', type: 'boolean', defaultValue: false, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'workflow.automaticApproval control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.manualReviewRequired', category: 'Competitor', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.manualReviewRequired control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.evidenceReferenceRequired', category: 'Competitor', type: 'boolean', defaultValue: true, scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.evidenceReferenceRequired control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'output.includeSummarySheet', category: 'Output', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'output.includeSummarySheet control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.saveRunMetadata', category: 'Privacy', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.saveRunMetadata control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.allowCompleteSnapshots', category: 'Privacy', type: 'boolean', defaultValue: false, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.allowCompleteSnapshots control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.autoClearOnTabClose', category: 'Privacy', type: 'boolean', defaultValue: false, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.autoClearOnTabClose control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.profileRetention', category: 'Privacy', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.profileRetention control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'privacy.aliasRetention', category: 'Privacy', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'privacy.aliasRetention control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.primaryIdentifier', category: 'Matching', type: 'enum', defaultValue: 'supplier-code', allowedValues: ['supplier-code', 'servicem8-item-number', 'gtin'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.primaryIdentifier control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'matching.duplicateHandling', category: 'Matching', type: 'enum', defaultValue: 'block', allowedValues: ['block', 'warn', 'manual-review'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'matching.duplicateHandling control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.missingCostSeverity', category: 'Validation', type: 'enum', defaultValue: 'blocking', allowedValues: ['warning', 'blocking'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.missingCostSeverity control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.zeroCostSeverity', category: 'Validation', type: 'enum', defaultValue: 'blocking', allowedValues: ['warning', 'blocking'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.zeroCostSeverity control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.negativeCostBehaviour', category: 'Validation', type: 'enum', defaultValue: 'block', allowedValues: ['block', 'warn'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.negativeCostBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.unsupportedCurrencyBehaviour', category: 'Validation', type: 'enum', defaultValue: 'block', allowedValues: ['block', 'warn'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.unsupportedCurrencyBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.unknownGstBehaviour', category: 'Validation', type: 'enum', defaultValue: 'block', allowedValues: ['block', 'warn'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.unknownGstBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.stockEligibility', category: 'Validation', type: 'enum', defaultValue: 'in-stock-only', allowedValues: ['in-stock-only', 'include-unknown'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.stockEligibility control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'validation.conditionEligibility', category: 'Validation', type: 'enum', defaultValue: 'new-only', allowedValues: ['new-only', 'include-used'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'validation.conditionEligibility control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.allowedCurrency', category: 'Competitor', type: 'enum', defaultValue: 'AUD', allowedValues: ['AUD'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.allowedCurrency control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.collectionMethod', category: 'Competitor', type: 'enum', defaultValue: 'manual', allowedValues: ['manual', 'paste', 'local-file'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.collectionMethod control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.recommendationStrategy', category: 'Competitor', type: 'enum', defaultValue: 'MATCH', allowedValues: ['MATCH', 'UNDERCUT_AMOUNT', 'UNDERCUT_PERCENT', 'MAINTAIN_FLOOR'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.recommendationStrategy control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.selectionMethod', category: 'Competitor', type: 'enum', defaultValue: 'lowest-valid-accepted', allowedValues: ['lowest-valid-accepted', 'newest-valid-accepted'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.selectionMethod control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'competitor.costFloorBehaviour', category: 'Competitor', type: 'enum', defaultValue: 'block-below-floor', allowedValues: ['block-below-floor'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'competitor.costFloorBehaviour control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'output.candidateTemplate', category: 'Output', type: 'enum', defaultValue: 'loaded-servicem8-export', allowedValues: ['loaded-servicem8-export', 'synthetic-candidate'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'output.candidateTemplate control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'output.auditDetailLevel', category: 'Output', type: 'enum', defaultValue: 'detailed', allowedValues: ['summary', 'detailed'], scopes: globalRun, confirmationRequired: false, impactPreviewRequired: true, helpText: 'output.auditDetailLevel control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'display.theme', category: 'Display', type: 'enum', defaultValue: 'system', allowedValues: ['system', 'light', 'dark', 'high-contrast'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'display.theme control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'display.tableDensity', category: 'Display', type: 'enum', defaultValue: 'comfortable', allowedValues: ['comfortable', 'compact'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'display.tableDensity control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'display.dateDisplay', category: 'Display', type: 'enum', defaultValue: 'local', allowedValues: ['local', 'iso'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'display.dateDisplay control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'display.timezone', category: 'Display', type: 'enum', defaultValue: 'browser', allowedValues: ['browser', 'UTC'], scopes: scopeAll, confirmationRequired: false, impactPreviewRequired: true, helpText: 'display.timezone control.', audit: 'change', schemaVersion: 1, migration: 'preserve', locked: false },
  { key: 'security.localProcessingOnly', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.localProcessingOnly control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noExternalRuntimeCalls', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noExternalRuntimeCalls control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noProductionWrites', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noProductionWrites control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noCompetitorScraping', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noCompetitorScraping control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.blockAmbiguousRecords', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.blockAmbiguousRecords control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.blockInvalidRecords', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.blockInvalidRecords control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noAutomaticMissingDeletes', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noAutomaticMissingDeletes control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.formulaInjectionProtection', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.formulaInjectionProtection control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.leadingZeroPreservation', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.leadingZeroPreservation control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'privacy.persistRawRowsByDefault', category: 'Locked safety invariants', type: 'boolean', defaultValue: false, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'privacy.persistRawRowsByDefault control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'output.onlyApprovedValidChanged', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'output.onlyApprovedValidChanged control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.costFloorEnforcement', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.costFloorEnforcement control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noArbitraryExpressionEvaluation', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noArbitraryExpressionEvaluation control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'security.noProductionReleaseAction', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'security.noProductionReleaseAction control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'privacy.cloudPersistence', category: 'Locked safety invariants', type: 'boolean', defaultValue: false, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'privacy.cloudPersistence control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'competitor.noLiveFetch', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'competitor.noLiveFetch control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'output.formulaInjectionProtection', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'output.formulaInjectionProtection control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'matching.leadingZeroPreservation', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'matching.leadingZeroPreservation control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
  { key: 'matching.blockAmbiguousAutomaticMatches', category: 'Locked safety invariants', type: 'boolean', defaultValue: true, scopes: globalRun, confirmationRequired: false, impactPreviewRequired: false, helpText: 'matching.blockAmbiguousAutomaticMatches control.', audit: 'security', schemaVersion: 1, migration: 'locked', locked: true },
] as const satisfies readonly SettingDefinition[];

export type ConfigValues = Record<string, unknown>;
export interface VersionedConfig { schemaVersion: number; values: ConfigValues; }

export function defaultConfig(): ConfigValues { return Object.fromEntries(SETTING_REGISTRY.map((setting) => [setting.key, setting.defaultValue])); }
export function registryByKey(): Map<string, SettingDefinition> { return new Map<string, SettingDefinition>(SETTING_REGISTRY.map((setting) => [setting.key, setting])); }
export function validateConfigImport(values: ConfigValues): string[] {
  const errors: string[] = []; const definitions = registryByKey();
  for (const key of Object.keys(values)) { const definition = definitions.get(key); if (!definition) { errors.push(`${key}: unknown setting`); continue; }
    if (definition.locked && values[key] !== definition.defaultValue) errors.push(`${key}: locked invariant cannot be changed`);
    if (definition.type === 'number') { const value = Number(values[key]); if (!Number.isFinite(value) || (definition.min ?? -Infinity) > value || value > (definition.max ?? Infinity)) errors.push(`${key}: outside allowed range`); }
    if (definition.type === 'enum' && definition.allowedValues && !(definition.allowedValues as readonly string[]).includes(String(values[key]))) errors.push(`${key}: unsupported value`);
    if (definition.type === 'boolean' && typeof values[key] !== 'boolean') errors.push(`${key}: must be true or false`);
    if (definition.type === 'string-list' && !Array.isArray(values[key])) errors.push(`${key}: must be a list`);
  } return errors; }
export function serialiseConfig(values: ConfigValues): VersionedConfig { return { schemaVersion: CONFIG_SCHEMA_VERSION, values }; }
export function deserialiseConfig(payload: VersionedConfig): { values: ConfigValues; errors: string[] } { const values = migrateConfig(payload); return { values, errors: validateConfigImport(values) }; }
export function migrateConfig(payload: VersionedConfig): ConfigValues { if (payload.schemaVersion !== 1) return defaultConfig(); return { ...defaultConfig(), ...payload.values }; }
export function resetConfigSection(values: ConfigValues, category: string): ConfigValues { const next = { ...values }; for (const setting of SETTING_REGISTRY) if (setting.category === category) next[setting.key] = setting.defaultValue; return next; }
export function changeImpact(key: string, value: unknown): string { const setting = registryByKey().get(key); if (!setting) return 'Unknown setting.'; return setting.impactPreviewRequired ? `${key} changes ${setting.category} behaviour to ${String(value)} and requires review.` : `${key} has no calculated business-row impact.`; }
export function resolveConfigValue(key: string, layers: Partial<Record<ConfigScope, ConfigValues>>) { const fallback = SETTING_REGISTRY.find((setting) => setting.key === key)?.defaultValue; for (const scope of ['run', 'product', 'category', 'supplier', 'global'] as const) { if (layers[scope] && key in layers[scope]) return { value: layers[scope]?.[key], source: scope }; } return { value: fallback, source: 'default' as const }; }
export function editableSettings() { return SETTING_REGISTRY.filter((setting) => !setting.locked); }
export function lockedSettings() { return SETTING_REGISTRY.filter((setting) => setting.locked); }
